os:
  - linux
#  - osx

language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

sudo: required

### # To get latex (but also need revtex4-1, emulateapj, and other classes for full test
before_install:
  - yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y --no-install-recommends
     texlive-fonts-recommended
     texlive-latex-extra
     texlive-latex-recommended
     texlive-publishers
     texlive-generic-recommended
     latex-xcolor

#  - wget http://hea-www.harvard.edu/~alexey/emulateapj/emulateapj.cls
#  - wget http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/mnras/mnras.cls
#  - wget http://journals.aas.org/authors/aastex/aastex61.cls

### - " --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
 
# Setup dependencies and install package
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION numpy nose 
  - source activate travis-env
  - python setup.py install

# command to run tests
script: 
  - nosetests --exe tests
  #- nosetests --exe -s tests
  #- nosetests --exe -s tests/test_journals.py:TestAuthlistFunc.test_aastex61
